### ISSUE TITLE
`cli::cli_inform()` vs `rlang::inform()`

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [r-lib/cli#426]
In our project, we use `{cli}` for user notification. I am looking into adopting newest versions of `{cli}` and `{rlang}`. 
I noticed failing snapshot test that showed that each time we output a message using `cli::cli_inform()`, I get an extra blank line before the printed message (*in the snapshot*). So if I run
```R
cli::cli_inform(text, class = class, .envir = env)
```
I get extra blanks. However, if I replace it with `{rlang}`, I get correct output
```R
rlang::inform(purrr::map_chr(text, cli::format_inline, .envir = env), class = class, call = env)
```
(I know these two calls are not identical operations)

Here is a diff of the snapshot we get while testing, note extra blank lines.
<details>
<summary>diff</summary>

```

  --- ".\\use_extendr.md"	2022-02-22 18:46:34.117975300 +0300
  +++ ".\\use_extendr.new.md"	2022-02-22 18:46:34.118974900 +0300
  @@ -2,18 +2,23 @@
   
       Code
         use_extendr()
       Message
  +      
         v Creating 'src/rust/src'.
         v Writing 'src/entrypoint.c'
         v Writing 'src/Makevars'
         v Writing 'src/Makevars.win'
         v Writing 'src/.gitignore'
  +      
         v Writing 'src/rust/Cargo.toml'
         v Writing 'src/rust/src/lib.rs'
         v Writing 'R/extendr-wrappers.R'
  +      
         v Finished configuring extendr for package testpkg.
  +      
         * Please update the system requirement in 'DESCRIPTION' file.
  +      
         * Please run `rextendr::document()` for changes to take effect.
   
   --- 
```
</details>

Messages not prefixed with a blank line are written using other tools (e.g., `usethis::write_over()`) and are therefore unaffected.
I do not observe extra blank lines in the console output when running the tested function manually.
So is this an issue or am I doing something wrong?

**Comment by gaborcsardi** [comment]
I think this was a bug in testthat that was already fixed.

**Comment by Ilia-Kosenkov** [comment]
I grabbed the dev version of `{testthat}` from github but it does not seem to solve the problem.

**Comment by gaborcsardi** [comment]
What goes in the snapshots is up to testthat, but in any case, do you have a reproducible example?

**Comment by Ilia-Kosenkov** [comment]
This is the best I can do:
```R
testthat::test_that("Check cli snapshot", {
  testthat::expect_snapshot({
    cli::cli_inform("Cli_1")
    cli::cli_inform("Cli_2")
    cli::cli_inform("Cli_3")

    rlang::inform("Rlang_1")
    rlang::inform("Rlang_2")
    rlang::inform("Rlang_3")
  })
})
```

<details>
<summary>And this is the output I get</summary>

```

# Check cli snapshot

    Code
      cli::cli_inform("Cli_1")
    Message
      
      Cli_1
    Code
      cli::cli_inform("Cli_2")
    Message
      
      Cli_2
    Code
      cli::cli_inform("Cli_3")
    Message
      
      Cli_3
    Code
      rlang::inform("Rlang_1")
    Message
      Rlang_1
    Code
      rlang::inform("Rlang_2")
    Message
      Rlang_2
    Code
      rlang::inform("Rlang_3")
    Message
      Rlang_3

```
</details>

**Comment by gaborcsardi** [comment]
Seems like testthat prints an empty like for the `\r` characters that cli outputs:
```r
❯ capture.output(type = "message", cli::cli_inform("Cli_1"))
[1] "\r\rCli_1" "\r\r"
```

I don't know if that is reasonable or not.

**Comment by gaborcsardi** [comment]
I am not sure if they are added by cli, actually. This is what is passed to rlang. How and why rlang would add `\r` I am not sure.

```r
❯ trace(rlang::inform, quote(print(c(list(...), as.list(environment())))))
Loading required package: rlang
Tracing function "inform" in package "rlang"
[1] "inform"

❯ cli::cli_inform("Cli_1")
Tracing rlang::inform(format_message(message, .envir = .envir), cli_bullets = message,  .... on entry
$cli_bullets
[1] "Cli_1"

$message
[1] "\033[1m\033[22mCli_1"

$class
NULL

$body
NULL

$footer
NULL

$use_cli_format
NULL

Cli_1
```

**Comment by gaborcsardi** [comment]
They are probably added when rlang calls back to cli to produce the output, and the goal is to clear the status line, if any.

**Comment by Ilia-Kosenkov** [comment]
I opened the issue because `cli::cli_inform()` actually calls into `rlang::inform()` https://github.com/r-lib/cli/blob/c389becc189ce73864c3b4cc41c2c98888692a9e/R/rlang.R#L66-L75
So I assumed the reason the output is malformed is that `{cli}` modifies the message sent to `{rlang}`. 

Actually, now that I checked the source once again, it seems that `escaped_message` is assigned but never used (line 68). Is that correct? `cli::cli_warn()` seems to use `escaped_message`. https://github.com/r-lib/cli/blob/c389becc189ce73864c3b4cc41c2c98888692a9e/R/rlang.R#L53-L61

Anyway, it seems that the source of the problem is `cli::cli_status("", "", "")`. I modified `cli::inform()` to 
```R
my_cli_inform <- function (message, ..., .envir = parent.frame()) {
    message[] <- cli:::vcapply(message, cli::format_inline, .envir = .envir)
    escaped_message <- cli:::cli_escape(message)
    # cli::cli_status("", "", "")
    rlang::inform(cli::format_message(message, .envir = .envir), cli_bullets = message, ...)
}
```
and executed these:
```R
capture.output(cli::cli_inform("Cli"), type = "message") |> print()
capture.output(my_cli_inform("MyCli"), type = "message") |> print()
capture.output(rlang::inform("Rlang"), type = "message") |> print()
```
and got:
```R
[1] "\r\rCli" "\r\r"   
[1] "MyCli"
[1] "Rlang"
```

**Comment by gaborcsardi** [comment]
Yes `cli::cli_status("", "", "")` erases the status bar. If we don't do this, then the rlang message would be printed after or on top of the cli status bar. There is no easy way to get rid of this, unfortunately.

**Comment by Ilia-Kosenkov** [comment]
Ok I see, feel free to close this issue then. Thanks for explanation!

**Comment by gaborcsardi** [comment]
I'll take one more look before the next release, to see if there is a way to detect if the status bar is empty, and then we don't need to emit the `\r`.

**Comment by hadley** [comment]
I think this behaviour is confusing me too. I see this in tests and at the console:

``` r
cli::cli_inform("Hello")
#> 
#> Hello
```

<sup>Created on 2022-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
OK, let's remove the status bar clearing for now, and we can fix the interference later.
